spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/VBAP_Reservation_System
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher